# Generated by Django 6.0.7 on 2026-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='Назва міста')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Час пошуку')),
                ('found', models.BooleanField(verbose_name='Успішно знайдено')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='Температура (°C)')),
            ],
            options={
                'verbose_name': 'Історія пошуку',
                'verbose_name_plural': 'Історія пошуків',
                'ordering': ['-searched_at'],
            },
        ),
    ]
